# Generated by Django 3.1.7 on 2021-03-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210313_2123'),
        ('teacher', '0002_auto_20210313_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clss1', models.CharField(max_length=50)),
                ('clss2', models.CharField(max_length=50)),
                ('clss3', models.CharField(max_length=50)),
                ('clss4', models.CharField(max_length=50)),
                ('clss5', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentprofile')),
            ],
        ),
    ]
