# Generated by Django 3.1.7 on 2021-03-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_founditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='found_item_image',
            field=models.ImageField(max_length=80, upload_to=''),
        ),
    ]
