# Generated by Django 3.1.7 on 2021-03-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
