# Generated by Django 3.1.7 on 2021-03-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0006_auto_20210316_2045'),
        ('user', '0002_auto_20210313_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.BooleanField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.founditem')),
                ('admin1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentprofile')),
            ],
        ),
    ]
